### ISSUE TITLE
Any chance you can port Inception-ResNet-v2 to keras?

### ISSUE THREAD

**Issue by jrao1** [kentsommer/keras-inceptionV4#1]
If I remember the paper correctly Inception-ResNet-v2 has comparable accuracy but trains faster.

BTW I think the paper URL formatting in README needs some fixing.

**Comment by kentsommer** [comment]
@jrao1 

Definitely a possibility. I'm going to be out of my lab due to Lunar New Year till next Tuesday but I'll take a look then and see how feasible it is.

(also fixed the formatting in the README)

**Comment by kentsommer** [comment]
@jrao1 

Looks to be relatively straightforward. When I've got some free time I'll throw it together and update the status here accordingly. I'm guessing I will have time within the next 2 weeks but it could take a month depending on how my current projects go.

**Comment by jrao1** [comment]
@kentsommer Ok, thanks for the update!

**Comment by kentsommer** [comment]
@jrao1 

I've pushed the model definition here: https://github.com/kentsommer/keras-inception-resnetV2

I'll be working on the weights either tomorrow or the day after (2/9 or 2/10). I'm closing out this issue, so please track progress at that repo!

You can run images through this model, however, since weights are randomly initialized the results are obviously not correct.

**Comment by jrao1** [comment]
@kentsommer Cool, I'll give it a try, thank you very much!
