### ISSUE TITLE
Image preprocess: why subtract by 1

### ISSUE THREAD

**Issue by zyxue** [kentsommer/keras-inceptionV4#11]
In Inception V3 at https://github.com/fchollet/deep-learning-models/blob/master/inception_v3.py#L391, preprocess is defined as 

```
def preprocess_input(x):
    x /= 255.
    x -= 0.5
    x *= 2.
    return x
```

But in Inception V4 at https://github.com/kentsommer/keras-inceptionV4/blob/keras-2/evaluate_image.py#L9

```
def preprocess_input(x):
    x = np.divide(x, 255.0)
    x = np.subtract(x, 1.0)
    x = np.multiply(x, 2.0)
    return x
```

I wonder why it becomes subtraction by 1 instead of 0.5? I thought 0.5 was easier to understand as it scaled the range to be between [-1, 1] after `x2`. Could you please point out where is the reference in the paper for the preprocessing steps? I couldn't find it at https://arxiv.org/pdf/1602.07261v1.pdf. Thanks!

FYI, I tried both values for the included [elephant](https://github.com/kentsommer/keras-inceptionV4/blob/master/elephant.jpg) image. Their certainties are

`x = np.subtract(x, 1.0)`: 0.852957
`x = np.subtract(x, 0.5)`: 0.775283

The second is lower, but still pretty high.

**Comment by zyxue** [comment]
In addition, if I removed the central_cropping step. The scores become

```
x = np.subtract(x, 1.0): 0.868853
x = np.subtract(x, 0.5): 0.84541
```
So the difference becomes smaller.

**Comment by kentsommer** [comment]
@zyxue 

I Left the default as 1 since it was what I used to obtain the performance metrics listed in the repo and I wanted those to be reproducible. 

There is no reference to using a subtraction of 1 in the paper as it is something I found (as you also saw) to slightly increase performance. Feel free to change it to 0.5 (perhaps I should change the default in the repo and make a note about how the performance metrics were obtained)

**Comment by kentsommer** [comment]
Closing out due to lack of activity.
