### ISSUE TITLE
Question about preprocessing

### ISSUE THREAD

**Issue by Hakuyume** [kentsommer/keras-inceptionV4#4]
A parameter of preprocessing seems different from the TensorFlow version.
In this Keras implementation, you subtract `1.0` from the image (https://github.com/kentsommer/keras-inceptionV4/blob/master/evaluate_image.py#L11).
On the other hand, in the TensorFlow implementation, they subtract `0.5` (https://github.com/tensorflow/models/blob/master/slim/preprocessing/inception_preprocessing.py#L273).

Why did you change this value?

**Comment by kentsommer** [comment]
I originally had left that value at ```0.5```, however, when I started crunching the performance numbers I noticed that performance increased somewhat if I used ```1.0``` instead. I'm not 100% sure why that would be the case, however, since I used it to achieve the performance metrics listed (which match the metrics [here](https://github.com/tensorflow/models/tree/master/slim)) I left the value at ```1.0``` for this release.

**Comment by Hakuyume** [comment]
Thank you for your quick response!
